spring.application.name=budgeting

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen2.5:1.5b
spring.ai.ollama.chat.think=false
spring.ai.ollama.chat.temperature=0.2
spring.ai.ollama.chat.num-predict=80
