import { StyleSheet } from 'react-native';
import { colors, radius } from './theme';

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.backgroundDeep }, safe: { flex: 1, backgroundColor: colors.background }, shell: { flex: 1, width: '100%', maxWidth: 720, alignSelf: 'center' }, scroll: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 122 },
  row: { flexDirection: 'row', alignItems: 'center' }, spread: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, header: { paddingBottom: 20 },
  avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: '#D4D9D0', shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 7, shadowOffset: { width: 0, height: 3 }, elevation: 4 }, avatarText: { color: colors.ink, fontWeight: '800', fontSize: 17 },
  iconButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', borderWidth: 4, borderColor: '#D4D9D0', shadowColor: '#000', shadowOpacity: 0.22, shadowRadius: 7, shadowOffset: { width: 0, height: 3 }, elevation: 4 }, iconButtonText: { color: colors.ink, fontSize: 20, fontWeight: '700' },
  greeting: { color: colors.white, fontSize: 24, fontWeight: '800', marginBottom: 5 }, subtitle: { color: colors.muted, fontSize: 14 },
  balancePanel: { borderRadius: radius.panel, padding: 20, marginTop: 18, marginBottom: 24, borderWidth: 1, borderColor: '#4B5A40', overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.26, shadowRadius: 18, shadowOffset: { width: 0, height: 12 }, elevation: 8 }, gloss: { position: 'absolute', left: 0, right: 0, top: 0, height: 65, backgroundColor: 'rgba(255,255,255,0.055)', borderBottomColor: 'rgba(255,255,255,0.06)', borderBottomWidth: 1 }, balanceLabel: { color: '#BCC3B6', fontSize: 12, fontWeight: '800', marginBottom: 6 }, balance: { color: colors.white, fontSize: 34, fontWeight: '800', letterSpacing: -1.2 }, trend: { color: colors.lime, fontSize: 12, fontWeight: '800', marginTop: 5 },
  bars: { height: 70, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', marginTop: 18, paddingHorizontal: 4 }, barWrap: { alignItems: 'center', width: '11%' }, bar: { width: 8, borderRadius: 8, backgroundColor: colors.white }, barAccent: { backgroundColor: colors.lime }, day: { color: colors.muted, fontSize: 10, marginTop: 8, fontWeight: '700' },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 18 }, primaryButton: { flex: 1, minHeight: 52, borderRadius: radius.pill, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, shadowColor: '#C9FF00', shadowOpacity: 0.17, shadowRadius: 9, shadowOffset: { width: 0, height: 4 } }, primaryText: { color: colors.ink, fontWeight: '800', fontSize: 15 }, secondaryButton: { flex: 1, minHeight: 52, borderRadius: radius.pill, backgroundColor: '#F5F6F1', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, secondaryText: { color: colors.ink, fontWeight: '800', fontSize: 15 },
  sectionTitle: { color: colors.white, fontSize: 18, fontWeight: '800' }, link: { color: colors.white, fontSize: 13, fontWeight: '700' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 14 }, categoryCard: { width: '47.9%', borderRadius: radius.card, padding: 15, minHeight: 116, borderWidth: 1, borderColor: '#435137', overflow: 'hidden', shadowColor: '#000', shadowOpacity: 0.17, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 4 }, categoryCardActive: { borderColor: '#D7FF00', shadowColor: '#D7FF00', shadowOpacity: 0.18 }, categoryIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EFF3EA', justifyContent: 'center', alignItems: 'center', marginBottom: 12 }, categoryTitle: { color: colors.white, fontSize: 13, fontWeight: '800' }, categoryValue: { color: colors.white, fontSize: 16, fontWeight: '800', marginTop: 5 }, categoryActiveText: { color: colors.ink },
  transaction: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.border }, transactionIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.surfaceSoft, alignItems: 'center', justifyContent: 'center', marginRight: 12, borderWidth: 1, borderColor: '#3B4932' }, transactionTitle: { color: colors.white, fontSize: 14, fontWeight: '800' }, transactionMeta: { color: colors.muted, fontSize: 12, marginTop: 3 }, transactionValue: { fontSize: 14, fontWeight: '800' },
  nav: { position: 'absolute', left: 20, right: 20, bottom: 22, minHeight: 70, borderRadius: 26, backgroundColor: 'rgba(248,249,244,0.96)', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', paddingHorizontal: 7, borderWidth: 1, borderColor: 'rgba(255,255,255,0.7)', shadowColor: '#000', shadowOpacity: 0.35, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 8 }, navItem: { flex: 1, alignItems: 'center', gap: 3, minHeight: 50, justifyContent: 'center' }, navIcon: { color: '#7D857A', fontSize: 19, fontWeight: '700' }, navLabel: { color: '#7D857A', fontSize: 10, fontWeight: '700' }, navActive: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#10200D', alignItems: 'center', justifyContent: 'center', marginTop: -27, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 8 }, navActiveText: { color: colors.lime, fontSize: 25, fontWeight: '800' },
  screenTitle: { color: colors.white, fontSize: 28, fontWeight: '800', marginBottom: 8 }, screenSubtitle: { color: colors.muted, fontSize: 14, marginBottom: 20 }, filterRow: { flexDirection: 'row', gap: 8, marginBottom: 10 }, filter: { borderRadius: radius.pill, paddingHorizontal: 14, paddingVertical: 9, backgroundColor: colors.surfaceSoft }, filterActive: { backgroundColor: colors.lime }, filterText: { color: colors.white, fontSize: 12, fontWeight: '800' }, filterActiveText: { color: colors.ink },
  summaryHero: { backgroundColor: colors.surface, borderRadius: radius.panel, padding: 22, marginBottom: 18 }, summaryCaption: { color: colors.muted, fontSize: 12, fontWeight: '700' }, summaryNumber: { color: colors.white, fontSize: 32, fontWeight: '800', marginTop: 6 }, metricRow: { flexDirection: 'row', gap: 12, marginBottom: 18 }, metric: { flex: 1, backgroundColor: colors.surface, padding: 15, borderRadius: radius.card }, metricLabel: { color: colors.muted, fontSize: 12 }, metricNumber: { color: colors.white, fontSize: 17, fontWeight: '800', marginTop: 7 }, ring: { width: 158, height: 158, borderRadius: 79, borderWidth: 20, borderColor: colors.lime, borderLeftColor: colors.surfaceSoft, borderBottomColor: colors.expense, alignSelf: 'center', alignItems: 'center', justifyContent: 'center', marginVertical: 20 }, ringText: { color: colors.white, fontWeight: '800', fontSize: 15 },
  profileCard: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.panel, padding: 26, marginBottom: 20 }, profileAvatar: { width: 80, height: 80, borderRadius: 40, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 12 }, profileName: { color: colors.white, fontSize: 21, fontWeight: '800' }, profileMail: { color: colors.muted, fontSize: 13, marginTop: 5 }, setting: { paddingVertical: 17, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: colors.border }, settingIcon: { width: 32, justifyContent: 'center', alignItems: 'flex-start' }, settingText: { color: colors.white, flex: 1, fontSize: 15, fontWeight: '700' }, settingArrow: { color: colors.muted, fontSize: 18 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.62)', justifyContent: 'flex-end' }, sheet: { backgroundColor: colors.surface, borderTopLeftRadius: 32, borderTopRightRadius: 32, padding: 22, minHeight: 360 }, sheetHandle: { height: 4, width: 44, backgroundColor: colors.muted, borderRadius: 3, alignSelf: 'center', marginBottom: 22 }, sheetTitle: { color: colors.white, fontSize: 23, fontWeight: '800' }, sheetCopy: { color: colors.muted, marginTop: 6, marginBottom: 22 }, textArea: { minHeight: 108, borderRadius: 20, backgroundColor: colors.surfaceMuted, borderWidth: 1, borderColor: colors.border, color: colors.white, padding: 16, textAlignVertical: 'top', fontSize: 16 }, recording: { alignItems: 'center', paddingVertical: 22 }, wave: { flexDirection: 'row', gap: 5, alignItems: 'center', height: 50 }, waveBar: { width: 5, borderRadius: 6, backgroundColor: colors.lime }, recordingText: { color: colors.white, fontSize: 16, fontWeight: '800', marginTop: 14 }, sheetActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  modalSuccess: { flex: 1, backgroundColor: colors.background, justifyContent: 'center', padding: 28 }, successCard: { backgroundColor: colors.surface, borderRadius: 32, padding: 26, alignItems: 'center' }, successBadge: { width: 76, height: 76, borderRadius: 38, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 16 }, successMark: { color: colors.ink, fontSize: 34, fontWeight: '900' }, successTitle: { color: colors.white, fontSize: 24, fontWeight: '800' }, successValue: { color: colors.expense, fontSize: 28, fontWeight: '800', marginVertical: 10 }, successMeta: { color: colors.muted, fontSize: 14 },
  auth: { flex: 1, padding: 28, justifyContent: 'center', width: '100%', maxWidth: 520, alignSelf: 'center' }, brand: { color: colors.lime, fontSize: 42, fontWeight: '900', letterSpacing: -2 }, authTitle: { color: colors.white, fontSize: 30, fontWeight: '800', marginTop: 44, lineHeight: 37 }, authCopy: { color: colors.muted, fontSize: 16, marginTop: 12, lineHeight: 23 }, dots: { flexDirection: 'row', gap: 8, marginTop: 35 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.surfaceSoft }, dotActive: { width: 26, backgroundColor: colors.lime }, authButton: { width: '100%', minHeight: 54, borderRadius: radius.pill, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginTop: 32 }, authButtonText: { color: colors.ink, fontSize: 16, fontWeight: '800' }, authLink: { color: colors.lime, fontSize: 14, fontWeight: '800', textAlign: 'center', marginTop: 19 }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 18, color: colors.white, fontSize: 16, minHeight: 54, paddingHorizontal: 16, marginTop: 12 }, inputLabel: { color: colors.muted, fontSize: 13, fontWeight: '700', marginTop: 21 }, back: { color: colors.muted, fontSize: 15, fontWeight: '700', marginBottom: 18 }, terms: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 15 },
});
